### ISSUE TITLE
TorchHook is not working on this version of syft.

### ISSUE THREAD

**Issue by 1901640100272** [MALLI7622/Federated-Blockchain-Anamoly-Detection#1]
I have tried to run the code but the syft.TorchHook is giving error and syft.Virtualworker is also giving error.
I think this is because of the newer versions of syft and Torch.
How can we run the code now?

**Comment by MALLI7622** [comment]
Hi @1901640100272  I did that project almost 3 years ago. PySyft has made some changes please refer to the original documentation.
